### ISSUE TITLE
Phosphate not included in the vocabulary

### ISSUE THREAD

**Issue by wenchangzhou-qtx** [Acellera/acegen-open#37]
Hey @MorganCThomas,

Thanks for guiding me here 😄 , I think "P" is not in the vocabulary inside prior directory, which is why when I have a phosphate provided as part of the promptsmiles, the run just failed but went through if I replace it with sulfur for example. Is there a reason not to have "P" there?

**Comment by MorganCThomas** [comment]
The vocabulary is built based on tokens found in the training dataset ergo the training dataset didn't contain any phosphorous. 

One option is to re-train a prior and manually specify that phosphorous is in the vocabulary, however, this would almost be futile because the model wouldn't learn anything about the use of phosphorous if it's not in the dataset, it'd have to rely on RL only. In this case, I think replacing it with a sulfur and could work.

The better option would be to re-train a prior on a dataset that contains many phosphorous compounds, so I suspect you should train your own prior to your needs, you can use the acegen-open/scripts/pretrain/pretrain_single_node.py to do this and following the instructions in the tutorials.

**Comment by wenchangzhou-qtx** [comment]
Hey @MorganCThomas,

Thanks for checking and suggestions. Actually gpt2 enamine_real model does have phosphorous and I need to unzip the checkpoint file first for me to try that. However, with the upzipped checkpoint file, I ran into this error:
```
Traceback (most recent call last):
  File "/home/softwares/acegen-open/scripts/reinvent/reinvent.py", line 118, in main
    run_reinvent(cfg, task)
  File "/home/softwares/acegen-open/scripts/reinvent/reinvent.py", line 147, in run_reinvent
    actor_training, actor_inference = create_actor(vocabulary_size=len(vocabulary))
  File "/home/softwares/mambaforge3/envs/acegen/lib/python3.10/site-packages/acegen/models/gpt2.py", line 114, in create_gpt2_actor
    config = define_gpt2_configuration(
  File "/home/softwares/mambaforge3/envs/acegen/lib/python3.10/site-packages/acegen/models/gpt2.py", line 87, in define_gpt2_configuration
    config = GPT2Config()
NameError: name 'GPT2Config' is not defined
```

**Comment by MorganCThomas** [comment]
Have you install the transformers library from hugging face?

**Comment by wenchangzhou-qtx** [comment]
I did not, now after installing it and run it I got the following error:
```
Traceback (most recent call last):
  File "/home/softwares/acegen-open/scripts/reinvent/reinvent.py", line 118, in main
    run_reinvent(cfg, task)
  File "/home/softwares/acegen-open/scripts/reinvent/reinvent.py", line 176, in run_reinvent
    env = create_env_fn()
  File "/home/softwares/acegen-open/scripts/reinvent/reinvent.py", line 173, in create_env_fn
    env.append_transform(get_primers_from_module(actor_training))
  File "/home/softwares/mambaforge3/envs/acegen/lib/python3.10/site-packages/torchrl/envs/transforms/transforms.py", line 885, in append_transform
    raise ValueError(
ValueError: TransformedEnv.append_transform expected a transform or a callable, but received an object of type <class 'NoneType'> instead.
```
Anything I'm still missing?

**Comment by MorganCThomas** [comment]
Ah yes, this was a bug we should have fixed today with #36.
Have you pulled the latest version of code?

**Comment by wenchangzhou-qtx** [comment]
Thanks, it's working with the latest code.
